# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nova_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nova_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12nova_control.proto\x12\x0cnova.control\"\xac\x01\n\x0fSemanticCommand\x12)\n\x04move\x18\x01 \x01(\x0b\x32\x19.nova.control.MoveCommandH\x00\x12)\n\x04stop\x18\x02 \x01(\x0b\x32\x19.nova.control.StopCommandH\x00\x12)\n\x04turn\x18\x03 \x01(\x0b\x32\x19.nova.control.TurnCommandH\x00\x12\x11\n\ttimestamp\x18\n \x01(\x01\x42\x05\n\x03\x63md\"1\n\x0bMoveCommand\x12\n\n\x02vx\x18\x01 \x01(\x02\x12\n\n\x02vy\x18\x02 \x01(\x02\x12\n\n\x02wz\x18\x03 \x01(\x02\"\r\n\x0bStopCommand\"\x1c\n\x0bTurnCommand\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02\"7\n\x0c\x41\x63tionVector\x12\x14\n\x0cjoint_angles\x18\x01 \x03(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\"\x12\n\x10SubscribeRequest\"\x85\x02\n\nRobotState\x12\x0c\n\x04qpos\x18\x01 \x03(\x02\x12\x0c\n\x04qvel\x18\x02 \x03(\x02\x12$\n\x08position\x18\x03 \x01(\x0b\x32\x12.nova.control.Vec3\x12\'\n\x0borientation\x18\x04 \x01(\x0b\x32\x12.nova.control.Quat\x12&\n\nlinear_vel\x18\x05 \x01(\x0b\x32\x12.nova.control.Vec3\x12\'\n\x0b\x61ngular_vel\x18\x06 \x01(\x0b\x32\x12.nova.control.Vec3\x12\x15\n\rfoot_contacts\x18\x07 \x03(\x08\x12\x11\n\tis_stable\x18\x08 \x01(\x08\x12\x11\n\ttimestamp\x18\t \x01(\x01\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\x32\xd7\x01\n\x0bNovaControl\x12\x42\n\x07\x43ommand\x12\x1d.nova.control.SemanticCommand\x1a\x18.nova.control.RobotState\x12;\n\x03\x41\x63t\x12\x1a.nova.control.ActionVector\x1a\x18.nova.control.RobotState\x12G\n\tSubscribe\x12\x1e.nova.control.SubscribeRequest\x1a\x18.nova.control.RobotState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nova_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEMANTICCOMMAND']._serialized_start=37
  _globals['_SEMANTICCOMMAND']._serialized_end=209
  _globals['_MOVECOMMAND']._serialized_start=211
  _globals['_MOVECOMMAND']._serialized_end=260
  _globals['_STOPCOMMAND']._serialized_start=262
  _globals['_STOPCOMMAND']._serialized_end=275
  _globals['_TURNCOMMAND']._serialized_start=277
  _globals['_TURNCOMMAND']._serialized_end=305
  _globals['_ACTIONVECTOR']._serialized_start=307
  _globals['_ACTIONVECTOR']._serialized_end=362
  _globals['_SUBSCRIBEREQUEST']._serialized_start=364
  _globals['_SUBSCRIBEREQUEST']._serialized_end=382
  _globals['_ROBOTSTATE']._serialized_start=385
  _globals['_ROBOTSTATE']._serialized_end=646
  _globals['_VEC3']._serialized_start=648
  _globals['_VEC3']._serialized_end=687
  _globals['_QUAT']._serialized_start=689
  _globals['_QUAT']._serialized_end=739
  _globals['_NOVACONTROL']._serialized_start=742
  _globals['_NOVACONTROL']._serialized_end=957
# @@protoc_insertion_point(module_scope)
