# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nova_control_pb2 as nova__control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nova_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NovaControlStub(object):
    """Nova 对外暴露的控制接口，Becoming / Demo 作为 client 调用
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Command = channel.unary_unary(
                '/nova.control.NovaControl/Command',
                request_serializer=nova__control__pb2.SemanticCommand.SerializeToString,
                response_deserializer=nova__control__pb2.RobotState.FromString,
                _registered_method=True)
        self.Act = channel.unary_unary(
                '/nova.control.NovaControl/Act',
                request_serializer=nova__control__pb2.ActionVector.SerializeToString,
                response_deserializer=nova__control__pb2.RobotState.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/nova.control.NovaControl/Subscribe',
                request_serializer=nova__control__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=nova__control__pb2.RobotState.FromString,
                _registered_method=True)


class NovaControlServicer(object):
    """Nova 对外暴露的控制接口，Becoming / Demo 作为 client 调用
    """

    def Command(self, request, context):
        """高层模式：语义指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Act(self, request, context):
        """端到端模式：直接关节角度（对齐 LeRobot 格式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """流式订阅机器人状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NovaControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=nova__control__pb2.SemanticCommand.FromString,
                    response_serializer=nova__control__pb2.RobotState.SerializeToString,
            ),
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=nova__control__pb2.ActionVector.FromString,
                    response_serializer=nova__control__pb2.RobotState.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=nova__control__pb2.SubscribeRequest.FromString,
                    response_serializer=nova__control__pb2.RobotState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nova.control.NovaControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nova.control.NovaControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NovaControl(object):
    """Nova 对外暴露的控制接口，Becoming / Demo 作为 client 调用
    """

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nova.control.NovaControl/Command',
            nova__control__pb2.SemanticCommand.SerializeToString,
            nova__control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nova.control.NovaControl/Act',
            nova__control__pb2.ActionVector.SerializeToString,
            nova__control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nova.control.NovaControl/Subscribe',
            nova__control__pb2.SubscribeRequest.SerializeToString,
            nova__control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
